openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/tutorial/1.0.0
    description: Local server
paths:
  /student/{student_id}:
    get:
      summary: gets student
      description: |
        Returns a single student
      operationId: get_student_by_id
      parameters:
      - name: student_id
        in: path
        description: the uid
        required: true
        style: simple
        explode: false
        schema:
          type: number
          format: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        "400":
          description: invalid ID
        "404":
          description: not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
    delete:
      summary: Deletes a student
      description: |
        Delete a single student by their unique identifier.
      operationId: delete_student
      parameters:
      - name: student_id
        in: path
        description: The unique identifier of the student
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successfully deleted the student.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad request. The request was invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "404":
          description: Not found. No student found with the provided ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /student:
    post:
      summary: Add a new student
      description: Adds an item to the system
      operationId: add_student
      requestBody:
        description: Student item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        "200":
          description: created
          content:
            application/json:
              schema:
                type: number
                format: integer
                x-content-type: application/json
        "400":
          description: "invalid input, object invalid"
        "409":
          description: an existing already exists
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Student:
      required:
      - first_name
      - last_name
      type: object
      properties:
        student_id:
          type: integer
          format: int64
          example: 12345
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        gradeRecords:
          type: array
          example:
          - subject_name: Mathematics
            grade: 8.5
          - subject_name: History
            grade: 7.2
          items:
            $ref: '#/components/schemas/GradeRecord'
      example:
        student_id: 12345
        last_name: Doe
        first_name: John
        gradeRecords:
        - subject_name: Mathematics
          grade: 8.5
        - subject_name: History
          grade: 7.2
    GradeRecord:
      required:
      - grade
      - subject_name
      type: object
      properties:
        subject_name:
          type: string
          example: Mathematics
        grade:
          maximum: 10
          minimum: 0
          type: number
          format: float
          example: 8.5
    inline_response_200:
      type: object
      properties:
        message:
          type: string
          example: Student successfully deleted.
      example:
        message: Student successfully deleted.
    inline_response_400:
      type: object
      properties:
        error:
          type: string
          example: Invalid student ID provided.
    inline_response_404:
      type: object
      properties:
        error:
          type: string
          example: Student not found with the provided ID.

